jerus-org/gen-changelog

CHANGELOG.md, build.rs
- move rerun-if-changed println statements to top of main function for clarity and maintainability
=> ♻️ refactor(build): reorder rerun-if-changed println calls

CHANGELOG.md, src/change_log.rs, src/change_log/section/cc_commit.rs
- change log level from debug to trace for finer-grained logging
=> ♻️ refactor(change_log): replace println with log macros

CHANGELOG.md, src/change_log.rs, src/config.rs, src/config/group.rs, src/config/group_mgmt.rs, src/lib.rs
- introduce config module to enhance modularity
- export Config for external use
=> ✨ feat(config): add new configuration settings for change log

CHANGELOG.md, src/config.rs
- introduce DisplaySections enum to control changelog section display
- implement default behavior and custom section count support
- add methods for getting and setting display sections in Config
=> ✨ feat(config): add display sections configuration

CHANGELOG.md, src/change_log/tag.rs
- remove macro for semver parsing, replace with `set_semver` method
- enhance trace and warning logging for semver extraction process
=> ♻️ refactor(tag): improve semver extraction logic

CHANGELOG.md, src/change_log.rs, src/change_log/header.rs, src/change_log/link.rs, src/change_log/section.rs, src/change_log/section/cc_commit.rs, src/main.rs
- implement clone trait for ConvCommit to enable struct duplication
=> ♻️ refactor(change_log): restructure ChangeLog and builder pattern

CHANGELOG.md, src/change_log.rs, src/change_log/section.rs
- enable processing of version tags to build sections from changelog
- support walking repository from tag to tag or release to start
=> ✨ feat(change_log): implement version tag processing

CHANGELOG.md, src/change_log/section.rs
- improve walking setup by using tags for more precise revision control
- enable commit retrieval and status reporting for release-to-release walks
=> ✨ feat(change_log): enhance release-to-release walking

CHANGELOG.md, src/change_log.rs, src/change_log/section.rs
- add missing line to push section into self.sections to fix changelog generation issue
=> ✨ feat(change_log): enhance section display formatting

CHANGELOG.md, src/config.rs, src/config/group.rs, src/config/group_mgmt.rs
- rename `set_no_publish` to `unset_publish` to enhance method readability and intent
=> ✨ feat(config): add unpublish_group method for changelog

CHANGELOG.md, src/change_log.rs, src/change_log/section.rs, src/config.rs, src/main.rs
- import `Config` for enhanced changelog customization
- introduce default config with debug logging
- add publish groups for Security, Chore, and Miscellaneous
=> ♻️ refactor(changelog): enhance section headings management

PRLOG.md, src/change_log.rs, src/change_log/link.rs, src/change_log/section.rs, src/change_log/section/section_header.rs, src/config.rs, src/main.rs
- group related imports together for better readability
- improve module structure by adjusting import paths
=> ♻️ refactor(change_log): enhance section struct with link support

PRLOG.md, src/change_log.rs, src/change_log/header.rs, src/main.rs
- implement save method to write changelog to CHANGELOG.md
- handle IO errors using ChangeLogError enum
=> ✨ feat(change_log): add save method for changelog

PRLOG.md, src/main.rs
- remove commented-out publish_group call for clarity
- remove unnecessary println statement for cleaner output
=> ♻️ refactor(main): clean up log and config usage

.circleci/config.yml, CHANGELOG.md, Cargo.toml, PRLOG.md, build.rs, justfile
- add `make_cargo_smart_release` command for cargo release automation
- introduce `make_smart_release` job to evaluate version and execute release
- enhance workflows with `make_smart_release` for improved CI efficiency
=> 🔧 chore: prepare for release

CHANGELOG.md, Cargo.toml, PRLOG.md, README.md, build.rs, docs/lib.md
- provide details on configuring ChangeLogConfig and ChangeLog structs
- include instructions for adding library to Cargo.toml using Cargo add
=> update library documentation with usage instructions

.circleci/config.yml, CHANGELOG.md, PRLOG.md
- remove pipefail option from shell settings to simplify command execution
- retain error checking and command tracing for better visibility and reliability
=> 👷 ci(circleci): update shell options in echo command

.circleci/config.yml, CHANGELOG.md, PRLOG.md
- add missing semicolons to case options to ensure proper execution
=> 👷 ci(circleci): fix case statement for version bump

.circleci/config.yml, CHANGELOG.md, PRLOG.md
- add installation steps for GitHub CLI for enhanced deployment
- remove unused parameters to streamline configuration
- update cargo smart-release command options for better release management
=> 👷 ci(circleci): update CircleCI config for improved build process

.circleci/config.yml, CHANGELOG.md, PRLOG.md
- add circleci/github-cli orb to simplify GitHub CLI installation
- replace manual GitHub CLI installation steps with orb command
=> 👷 ci(circleci): integrate GitHub CLI using official orb

.vscode/settings.json, CHANGELOG.md, Cargo.toml, PRLOG.md
- move authors field for better readability and consistency with other fields
=> 💄 style(Cargo): reorder authors in Cargo.toml

.circleci/config.yml, PRLOG.md
- add missing backslash for multi-line command continuation
=> 👷 ci(circleci): fix command syntax in config.yml

Cargo.toml, PRLOG.md
- add CHANGELOG.md to the included files in Cargo.toml
- ensure changelog is part of the package distribution
=> 🔧 chore(Cargo): include changelog in package distribution

.circleci/config.yml, PRLOG.md, release-hook.sh
- append changelog generation step to the release script for better documentation of changes
- ensure changelog is updated with each release
=> 👷 ci(circleci): update release command configuration

PRLOG.md, src/main.rs
- enhance command handling by integrating command parsing into run function
- refactor main to incorporate new command structure and execution flow
=> ♻️ refactor(main): improve command parsing and execution

Cargo.lock, Cargo.toml, PRLOG.md, examples/demo_headings.rs, src/change_log.rs, src/change_log_config.rs, src/change_log_config/group.rs, src/change_log_config/heading_serde.rs, src/change_log_config/test_config_serialization.rs
- remove underscore prefix from config variable to indicate usage
- uncomment config.save() to enable saving functionality
=> ✨ feat(config): enhance changelog config with serde support

PRLOG.md, src/change_log_config.rs, src/error.rs, src/main.rs
- change configuration initialization to use from_file_or_default for flexibility
- comment out custom display section setting for future consideration
- add debug print for configuration state
=> ✨ feat(config): add file-based config initialization

PRLOG.md, src/change_log.rs, src/lib.rs, src/main.rs
- add ChangeLogBuilder to public exports for improved API usability
=> ✨ feat(main): add support for setting next version in changelog

PRLOG.md, release-hook.sh
- add shellcheck directive to disable SC2129 warning when appending to README.md
=> 💄 style(shell): add shellcheck directive for appending

.vscode/ltex.dictionary.en-GB.txt, .vscode/ltex.hiddenFalsePositives.en-GB.txt, PRLOG.md, docs/lib.md, docs/readme/lib.md, release-hook.sh
- add comprehensive usage examples and installation instructions
- include detailed descriptions of core components and default configuration
- expand on error handling and requirements for the library usage
=> 📝 docs(lib): enhance gen-changelog library documentation

PRLOG.md, src/change_log.rs, src/change_log_config.rs, src/lib.rs
- change visibility of DisplaySections enum to crate level
- change visibility of display_sections method to crate level
=> ♻️ refactor(change_log_config): restrict enum and method visibility

Cargo.lock, Cargo.toml, PRLOG.md, benches/config_log.rs
- add criterion 0.7.0 to dev dependencies for benchmarking
- add tempfile 3.22.0 to dev dependencies for handling temporary files
- configure a new benchmark named config_log with harness disabled
=> 📦 build(dependencies): update dev dependencies and add benchmark

PRLOG.md, src/change_log.rs
- include tests for regex patterns, builder creation, and formatting
- add performance and concurrency tests for changelog operations
- verify handling of special characters and unicode in headers
- ensure documentation examples are tested and validated
=> ✅ test(change_log): add comprehensive unit tests for changelog module

PRLOG.md, docs/readme/head.md
- update capitalization of Gen-changelog for consistency with naming conventions
=> 📝 docs(README): correct capitalization of Gen-changelog

PRLOG.md, docs/readme/head.md
- change splash image URL to point to splash2.svg for updated visuals
=> 📝 docs(README)!: update splash image link

PRLOG.md, src/generate_cli.rs
- introduce no_save flag to prevent saving changelog
- enhance flexibility for changelog generation process
=> ✨ feat(generate_cli): add no-save option for changelog

.circleci/config.yml, PRLOG.md
- bump toolkit version from 2.13.0 to 2.13.1
=> 👷 ci(circleci): update circleci toolkit orb version
