jerus-org/gen-changelog

CHANGELOG.md, Cargo.lock, Cargo.toml, src/change_log.rs, src/change_log/link.rs
- add link module and use Vec<Link> instead of String for links
- remove footer field and related methods from ChangeLog
- simplify ChangeLog initialization by eliminating default footer initialization
=> ✨ feat(change_log): add link module for URL handling

CHANGELOG.md, src/change_log.rs, src/change_log/section.rs
- rename `FromTagtoTag` to `FromReleaseToRelease` for clarity
- add `get_commits` method to handle commit retrieval
- enhance logging for clearer debugging information
=> ♻️ refactor(change_log): update walk setup naming

CHANGELOG.md, src/config/group_mgmt.rs
- use Group struct for adding groups
- implement methods to create group instances in tests
♻️ refactor(config): switch from BTreeMap to HashMap for group management
- replace BTreeMap with HashMap for storing groups
- update GroupMgmt trait to use Group struct
- remove miscellaneous group handling logic
- adapt unit tests to new data structure
=> ✨ feat(group): introduce Group struct in group management

CHANGELOG.md, src/config/heading_mgmt.rs
- increment heading index by 1 to start order from 1
- ensure proper numbering for group headings in BTreeMap
=> 🐛 fix(config): correct heading index initialization

CHANGELOG.md, src/change_log/section.rs
- remove redundant vectors for commit classification
- utilize a single BTreeMap for storing categorized commits
=> ♻️ refactor(change_log): simplify commit classification

CHANGELOG.md, src/change_log/section.rs, src/change_log/section/cc_commit.rs
- change return type of kind_string from String to Option<String>
- enable handling of cases where kind is not present
=> ♻️ refactor(cc_commit): change return type of kind_string method

PRLOG.md, src/change_log/section.rs, src/change_log/section/cc_commit.rs
- delete title_as_string method from ConvCommit as it is no longer used
=> ♻️ refactor(cc_commit): remove unused title_as_string function

PRLOG.md, src/config.rs
- introduce groups_mapping field using BTreeMap to store group mappings
- update default implementation to populate groups_mapping with convention commit types
- add groups_mapping method for accessing the mapping data
=> ✨ feat(config): add groups mapping for conventional commits

.circleci/config.yml, PRLOG.md
- change variable $BUMP to lowercase $bump to match script requirements
=> 👷 ci(circleci): fix variable casing in release command

.circleci/config.yml, PRLOG.md
- add verbosity parameter to cargo release commands
- ensure no-confirm flag is used for non-interactive execution
=> 👷 ci(circleci): enhance cargo release commands with verbosity

PRLOG.md, release.toml
- correct search term from "gen-change" to "gen-changelog" in docs/lib.md
- ensure accurate versioning replacements during release process
=> 🔧 chore(release): update pre-release replacements in release.toml

.circleci/config.yml, Cargo.lock, Cargo.toml, PRLOG.md
- include command to install gen-changelog using cargo in CI pipeline
- ensure changelog generation tool is available for automated tasks
=> 👷 ci(circleci): add gen-changelog installation step

PRLOG.md, src/change_log_config.rs, src/lib.rs, src/main.rs
- introduce DisplaySections to customize changelog display
- set display sections to custom value for better flexibility
🐛 fix(main): enable saving of changelog configuration
- fix configuration saving by uncommenting save method
- add log information for saving action
=> ✨ feat(lib): export DisplaySections from change_log_config

PRLOG.md, src/change_log.rs, src/change_log/section.rs, src/change_log_config.rs, src/error.rs, src/lib.rs, src/main.rs
- change `ChangeLogError` to `GcError` for clearer error handling
- update function signatures to use the new error type alias
=> ✨ feat(error): add custom error handling with thiserror

.vscode/settings.json, PRLOG.md, src/change_log.rs, src/change_log_config.rs, src/change_log_config/test_config_serialization.rs
- add comments for group tables definition and usage
- introduce comments for display order of groups and sections
- remove unnecessary group mappings field from ChangeLogConfig
- implement dynamic group mapping generation in method
♻️ refactor(change_log_config): update changelog save logic
- insert comments into TOML string before saving configuration file
- modify logic to ensure comments are added at correct positions
=> ✨ feat(changelog): add comments for changelog configuration

PRLOG.md, docs/main.md
- rename title and references to "Gen-changelog CLI" for consistency
- fix spelling to align with British English conventions
=> 📝 docs(README): update Gen-changelog CLI documentation

PRLOG.md, src/change_log_config.rs
- Add detailed comments and examples for default groups configuration
- Document fields and methods in the ChangeLogConfig struct
- Include examples for method chaining and configuration file format
- Improve clarity on display sections and release pattern usage
=> 📝 docs(config): enhance documentation for changelog configuration

PRLOG.md, src/change_log_config.rs
- Implement unit tests for various functionalities within ChangeLogConfig
- Ensure coverage for default configuration and serialization
- Test serialization and deserialization of config variants
- Validate file operations and default behaviors in absence of config file
=> ✅ test(change_log_config): add comprehensive tests for ChangeLogConfig

PRLOG.md, docs/lib.md, src/change_log.rs, src/change_log_config.rs
- change examples from `change_log` to `gen_changelog` for accuracy
- add missing imports and main function in examples for clarity
=> 📝 docs(changelog): update code examples 

PRLOG.md, docs/lib.md, src/change_log.rs, src/generate_cli.rs, src/lib.rs
- introduce a new `name` option to specify the changelog file name
- set default value for `name` as "CHANGELOG.md"
=> ✨ feat(cli): add name option for changelog file
